# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK-ObjC-project-BMV' do
    pod 'Masonry', '~> 1.1'

  target 'VK-ObjC-project-BMVTests' do
    inherit! :search_paths
     pod ‘OCMock’, '~> 3.4.1’
     pod 'Expecta', '~> 1.0'
  end
end
