# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK-ObjC-project-BMV' do
  # Pods for VK-ObjC-project-BMV
    pod 'Masonry', '~> 1.1'

  target 'VK-ObjC-project-BMVTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Expecta', '~> 1.0'
    pod 'OCMock', '~> 3.4'

  end

  target 'VK-ObjC-project-BMVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
